name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hacer checkout del repositorio
      uses: actions/checkout@v3
  
    - name: Hacer login en dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
  
    - name: Crear y compilar imagen
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/sql-server:latest
        
    - name: Notificación de la imagen (digest)
      run: echo ${{ steps.docker_build.outputs.digest }}
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
